# Generated by Django 6.0 on 2025-12-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_socials_alter_about_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='SocialLink',
        ),
    ]
